// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeUser = `-- name: AnonymizeUser :one
UPDATE users
SET email = 'anon-' || gen_random_uuid()::text || '@deleted.local',
    display_name = NULL,
    locale = 'fr',
    reputation_score = 0,
    email_verified_at = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE id = $1::uuid AND deleted_at IS NULL
RETURNING id, email, display_name, role, locale, reputation_score, email_verified_at, created_at, updated_at, deleted_at
`

type AnonymizeUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) AnonymizeUser(ctx context.Context, id pgtype.UUID) (AnonymizeUserRow, error) {
	row := q.db.QueryRow(ctx, anonymizeUser, id)
	var i AnonymizeUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, expires_at, user_agent, ip_address)
VALUES (
    $1::uuid,
    $2::char(64),
    $3::timestamptz,
    $4::text,
    $5::inet
)
RETURNING id, user_id, refresh_token_hash, expires_at, created_at, updated_at, revoked_at, user_agent, ip_address
`

type CreateSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, locale)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::varchar
)
RETURNING id, email, display_name, role, locale, reputation_score, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	DisplayName  *string `json:"display_name"`
	Locale       string  `json:"locale"`
}

type CreateUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Locale,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, expires_at, created_at, updated_at, revoked_at, user_agent, ip_address FROM sessions
WHERE refresh_token_hash = $1::char(64)
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, role, locale, reputation_score, email_verified_at, created_at, updated_at, deleted_at
FROM users
WHERE email = $1::text
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, display_name, role, locale, reputation_score, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1::uuid
`

type GetUserByIdRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFuelPriceContributions = `-- name: ListFuelPriceContributions :many
SELECT
    o.id,
    o.amount_per_litre,
    o.currency,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.created_at,
    f.code AS fuel_type_code,
    f.name_i18n AS fuel_type_name_i18n,
    l.id AS location_id,
    l.name AS location_name,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM fuel_price_observations AS o
JOIN fuel_types AS f ON f.id = o.fuel_type_id
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.contributor_id = $1::uuid
ORDER BY o.created_at DESC, o.id
LIMIT $3::integer OFFSET $2::integer
`

type ListFuelPriceContributionsParams struct {
	ContributorID pgtype.UUID `json:"contributor_id"`
	PageOffset    int32       `json:"page_offset"`
	PageSize      int32       `json:"page_size"`
}

type ListFuelPriceContributionsRow struct {
	ID               pgtype.UUID        `json:"id"`
	AmountPerLitre   pgtype.Numeric     `json:"amount_per_litre"`
	Currency         string             `json:"currency"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FuelTypeCode     string             `json:"fuel_type_code"`
	FuelTypeNameI18n []byte             `json:"fuel_type_name_i18n"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
}

func (q *Queries) ListFuelPriceContributions(ctx context.Context, arg ListFuelPriceContributionsParams) ([]ListFuelPriceContributionsRow, error) {
	rows, err := q.db.Query(ctx, listFuelPriceContributions, arg.ContributorID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFuelPriceContributionsRow{}
	for rows.Next() {
		var i ListFuelPriceContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountPerLitre,
			&i.Currency,
			&i.ObservedAt,
			&i.Status,
			&i.ConfidenceScore,
			&i.CreatedAt,
			&i.FuelTypeCode,
			&i.FuelTypeNameI18n,
			&i.LocationID,
			&i.LocationName,
			&i.GeoAreaID,
			&i.GeoAreaName,
			&i.SourceID,
			&i.SourceName,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPriceContributions = `-- name: ListProductPriceContributions :many
SELECT
    o.id,
    o.amount,
    o.currency,
    o.quantity,
    o.unit_code,
    o.is_promotion,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.created_at,
    p.name AS product_name,
    l.id AS location_id,
    l.name AS location_name,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM product_price_observations AS o
JOIN products AS p ON p.id = o.product_id
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.contributor_id = $1::uuid
ORDER BY o.created_at DESC, o.id
LIMIT $3::integer OFFSET $2::integer
`

type ListProductPriceContributionsParams struct {
	ContributorID pgtype.UUID `json:"contributor_id"`
	PageOffset    int32       `json:"page_offset"`
	PageSize      int32       `json:"page_size"`
}

type ListProductPriceContributionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitCode        string             `json:"unit_code"`
	IsPromotion     bool               `json:"is_promotion"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProductName     string             `json:"product_name"`
	LocationID      pgtype.UUID        `json:"location_id"`
	LocationName    string             `json:"location_name"`
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName     string             `json:"geo_area_name"`
	SourceID        pgtype.UUID        `json:"source_id"`
	SourceName      string             `json:"source_name"`
	SourceKind      SourceKind         `json:"source_kind"`
}

func (q *Queries) ListProductPriceContributions(ctx context.Context, arg ListProductPriceContributionsParams) ([]ListProductPriceContributionsRow, error) {
	rows, err := q.db.Query(ctx, listProductPriceContributions, arg.ContributorID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductPriceContributionsRow{}
	for rows.Next() {
		var i ListProductPriceContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitCode,
			&i.IsPromotion,
			&i.ObservedAt,
			&i.Status,
			&i.ConfidenceScore,
			&i.CreatedAt,
			&i.ProductName,
			&i.LocationID,
			&i.LocationName,
			&i.GeoAreaID,
			&i.GeoAreaName,
			&i.SourceID,
			&i.SourceName,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :execrows
UPDATE sessions
SET revoked_at = now(), updated_at = now()
WHERE user_id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now(), updated_at = now()
WHERE id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionRefresh = `-- name: UpdateSessionRefresh :one
UPDATE sessions
SET refresh_token_hash = $1::char(64),
    expires_at = $2::timestamptz,
    updated_at = now()
WHERE id = $3::uuid AND revoked_at IS NULL
RETURNING id, user_id, refresh_token_hash, expires_at, created_at, updated_at, revoked_at, user_agent, ip_address
`

type UpdateSessionRefreshParams struct {
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ID               pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateSessionRefresh(ctx context.Context, arg UpdateSessionRefreshParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionRefresh, arg.RefreshTokenHash, arg.ExpiresAt, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $1::text,
    locale = $2::varchar,
    updated_at = now()
WHERE id = $3::uuid
RETURNING id, email, display_name, role, locale, reputation_score, email_verified_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName *string     `json:"display_name"`
	Locale      string      `json:"locale"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateUserProfileRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.Locale, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
