// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: contributions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFuelContribution = `-- name: DeleteFuelContribution :execrows
DELETE FROM fuel_price_observations
WHERE id = $1::uuid
  AND contributor_id = $2::uuid
  AND status = 'pending'
`

type DeleteFuelContributionParams struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
}

func (q *Queries) DeleteFuelContribution(ctx context.Context, arg DeleteFuelContributionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFuelContribution, arg.ID, arg.ContributorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductContribution = `-- name: DeleteProductContribution :execrows
DELETE FROM product_price_observations
WHERE id = $1::uuid
  AND contributor_id = $2::uuid
  AND status = 'pending'
`

type DeleteProductContributionParams struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
}

func (q *Queries) DeleteProductContribution(ctx context.Context, arg DeleteProductContributionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductContribution, arg.ID, arg.ContributorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommunitySourceID = `-- name: GetCommunitySourceID :one
SELECT id
FROM sources
WHERE kind = 'community'
ORDER BY created_at ASC, id
LIMIT 1
`

func (q *Queries) GetCommunitySourceID(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCommunitySourceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getFuelContribution = `-- name: GetFuelContribution :one
SELECT
    o.id,
    o.contributor_id,
    o.amount_per_litre,
    o.currency,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.created_at,
    f.code AS fuel_type_code,
    f.name_i18n AS fuel_type_name_i18n,
    l.id AS location_id,
    l.name AS location_name,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM fuel_price_observations AS o
JOIN fuel_types AS f ON f.id = o.fuel_type_id
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.id = $1::uuid
`

type GetFuelContributionRow struct {
	ID               pgtype.UUID        `json:"id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	AmountPerLitre   pgtype.Numeric     `json:"amount_per_litre"`
	Currency         string             `json:"currency"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	FuelTypeCode     string             `json:"fuel_type_code"`
	FuelTypeNameI18n []byte             `json:"fuel_type_name_i18n"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
}

func (q *Queries) GetFuelContribution(ctx context.Context, id pgtype.UUID) (GetFuelContributionRow, error) {
	row := q.db.QueryRow(ctx, getFuelContribution, id)
	var i GetFuelContributionRow
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.AmountPerLitre,
		&i.Currency,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.CreatedAt,
		&i.FuelTypeCode,
		&i.FuelTypeNameI18n,
		&i.LocationID,
		&i.LocationName,
		&i.GeoAreaID,
		&i.GeoAreaName,
		&i.SourceID,
		&i.SourceName,
		&i.SourceKind,
	)
	return i, err
}

const getProductContribution = `-- name: GetProductContribution :one
SELECT
    o.id,
    o.contributor_id,
    o.amount,
    o.currency,
    o.quantity,
    o.unit_code,
    o.is_promotion,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.created_at,
    p.name AS product_name,
    l.id AS location_id,
    l.name AS location_name,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM product_price_observations AS o
JOIN products AS p ON p.id = o.product_id
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.id = $1::uuid
`

type GetProductContributionRow struct {
	ID              pgtype.UUID        `json:"id"`
	ContributorID   pgtype.UUID        `json:"contributor_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitCode        string             `json:"unit_code"`
	IsPromotion     bool               `json:"is_promotion"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProductName     string             `json:"product_name"`
	LocationID      pgtype.UUID        `json:"location_id"`
	LocationName    string             `json:"location_name"`
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName     string             `json:"geo_area_name"`
	SourceID        pgtype.UUID        `json:"source_id"`
	SourceName      string             `json:"source_name"`
	SourceKind      SourceKind         `json:"source_kind"`
}

func (q *Queries) GetProductContribution(ctx context.Context, id pgtype.UUID) (GetProductContributionRow, error) {
	row := q.db.QueryRow(ctx, getProductContribution, id)
	var i GetProductContributionRow
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.UnitCode,
		&i.IsPromotion,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.CreatedAt,
		&i.ProductName,
		&i.LocationID,
		&i.LocationName,
		&i.GeoAreaID,
		&i.GeoAreaName,
		&i.SourceID,
		&i.SourceName,
		&i.SourceKind,
	)
	return i, err
}

const insertFuelContribution = `-- name: InsertFuelContribution :one
INSERT INTO fuel_price_observations (
    fuel_type_id,
    location_id,
    source_id,
    contributor_id,
    amount_per_litre,
    currency,
    observed_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::numeric,
    $6::char(3),
    $7::timestamptz
)
RETURNING id, status
`

type InsertFuelContributionParams struct {
	FuelTypeID     pgtype.UUID        `json:"fuel_type_id"`
	LocationID     pgtype.UUID        `json:"location_id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	ContributorID  pgtype.UUID        `json:"contributor_id"`
	AmountPerLitre pgtype.Numeric     `json:"amount_per_litre"`
	Currency       string             `json:"currency"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
}

type InsertFuelContributionRow struct {
	ID     pgtype.UUID      `json:"id"`
	Status ModerationStatus `json:"status"`
}

func (q *Queries) InsertFuelContribution(ctx context.Context, arg InsertFuelContributionParams) (InsertFuelContributionRow, error) {
	row := q.db.QueryRow(ctx, insertFuelContribution,
		arg.FuelTypeID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.AmountPerLitre,
		arg.Currency,
		arg.ObservedAt,
	)
	var i InsertFuelContributionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertProductContribution = `-- name: InsertProductContribution :one
INSERT INTO product_price_observations (
    product_id,
    location_id,
    source_id,
    contributor_id,
    amount,
    currency,
    quantity,
    unit_code,
    normalized_amount,
    is_promotion,
    observed_at
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::numeric,
    $6::char(3),
    $7::numeric,
    $8::varchar,
    $9::numeric,
    $10::boolean,
    $11::timestamptz
)
RETURNING id, status
`

type InsertProductContributionParams struct {
	ProductID        pgtype.UUID        `json:"product_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
}

type InsertProductContributionRow struct {
	ID     pgtype.UUID      `json:"id"`
	Status ModerationStatus `json:"status"`
}

func (q *Queries) InsertProductContribution(ctx context.Context, arg InsertProductContributionParams) (InsertProductContributionRow, error) {
	row := q.db.QueryRow(ctx, insertProductContribution,
		arg.ProductID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.UnitCode,
		arg.NormalizedAmount,
		arg.IsPromotion,
		arg.ObservedAt,
	)
	var i InsertProductContributionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const updateFuelContribution = `-- name: UpdateFuelContribution :one
UPDATE fuel_price_observations
SET amount_per_litre = $1::numeric,
    currency = $2::char(3),
    observed_at = $3::timestamptz
WHERE id = $4::uuid
  AND contributor_id = $5::uuid
  AND status = 'pending'
RETURNING id
`

type UpdateFuelContributionParams struct {
	AmountPerLitre pgtype.Numeric     `json:"amount_per_litre"`
	Currency       string             `json:"currency"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	ID             pgtype.UUID        `json:"id"`
	ContributorID  pgtype.UUID        `json:"contributor_id"`
}

func (q *Queries) UpdateFuelContribution(ctx context.Context, arg UpdateFuelContributionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateFuelContribution,
		arg.AmountPerLitre,
		arg.Currency,
		arg.ObservedAt,
		arg.ID,
		arg.ContributorID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProductContribution = `-- name: UpdateProductContribution :one
UPDATE product_price_observations
SET amount = $1::numeric,
    currency = $2::char(3),
    quantity = $3::numeric,
    unit_code = $4::varchar,
    normalized_amount = $5::numeric,
    is_promotion = $6::boolean,
    observed_at = $7::timestamptz
WHERE id = $8::uuid
  AND contributor_id = $9::uuid
  AND status = 'pending'
RETURNING id
`

type UpdateProductContributionParams struct {
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	ID               pgtype.UUID        `json:"id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
}

func (q *Queries) UpdateProductContribution(ctx context.Context, arg UpdateProductContributionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateProductContribution,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.UnitCode,
		arg.NormalizedAmount,
		arg.IsPromotion,
		arg.ObservedAt,
		arg.ID,
		arg.ContributorID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
