// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: imports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addImportRow = `-- name: AddImportRow :exec
INSERT INTO import_rows (import_id, line_number, payload)
VALUES ($1::uuid, $2::integer, $3::jsonb)
`

type AddImportRowParams struct {
	ImportID   pgtype.UUID `json:"import_id"`
	LineNumber int32       `json:"line_number"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) AddImportRow(ctx context.Context, arg AddImportRowParams) error {
	_, err := q.db.Exec(ctx, addImportRow, arg.ImportID, arg.LineNumber, arg.Payload)
	return err
}

const createImport = `-- name: CreateImport :one
INSERT INTO imports (resource_type, created_by, line_count)
VALUES ($1::text, $2::uuid, $3::integer)
RETURNING id, resource_type, status, created_by, line_count, valid_count, invalid_count, report, created_at, validated_at, published_at
`

type CreateImportParams struct {
	ResourceType string      `json:"resource_type"`
	CreatedBy    pgtype.UUID `json:"created_by"`
	LineCount    int32       `json:"line_count"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, createImport, arg.ResourceType, arg.CreatedBy, arg.LineCount)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.Status,
		&i.CreatedBy,
		&i.LineCount,
		&i.ValidCount,
		&i.InvalidCount,
		&i.Report,
		&i.CreatedAt,
		&i.ValidatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getImport = `-- name: GetImport :one
SELECT id, resource_type, status, created_by, line_count, valid_count, invalid_count, report, created_at, validated_at, published_at FROM imports WHERE id = $1::uuid
`

func (q *Queries) GetImport(ctx context.Context, id pgtype.UUID) (Import, error) {
	row := q.db.QueryRow(ctx, getImport, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.ResourceType,
		&i.Status,
		&i.CreatedBy,
		&i.LineCount,
		&i.ValidCount,
		&i.InvalidCount,
		&i.Report,
		&i.CreatedAt,
		&i.ValidatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listImportRows = `-- name: ListImportRows :many
SELECT id, line_number, payload, valid, error
FROM import_rows
WHERE import_id = $1::uuid
ORDER BY line_number
`

type ListImportRowsRow struct {
	ID         pgtype.UUID `json:"id"`
	LineNumber int32       `json:"line_number"`
	Payload    []byte      `json:"payload"`
	Valid      *bool       `json:"valid"`
	Error      *string     `json:"error"`
}

func (q *Queries) ListImportRows(ctx context.Context, importID pgtype.UUID) ([]ListImportRowsRow, error) {
	rows, err := q.db.Query(ctx, listImportRows, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportRowsRow{}
	for rows.Next() {
		var i ListImportRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.LineNumber,
			&i.Payload,
			&i.Valid,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImports = `-- name: ListImports :many
SELECT id, resource_type, status, created_by, line_count, valid_count, invalid_count, report, created_at, validated_at, published_at FROM imports ORDER BY created_at DESC LIMIT $2::integer OFFSET $1::integer
`

type ListImportsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListImports(ctx context.Context, arg ListImportsParams) ([]Import, error) {
	rows, err := q.db.Query(ctx, listImports, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Import{}
	for rows.Next() {
		var i Import
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.Status,
			&i.CreatedBy,
			&i.LineCount,
			&i.ValidCount,
			&i.InvalidCount,
			&i.Report,
			&i.CreatedAt,
			&i.ValidatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImportPublished = `-- name: MarkImportPublished :exec
UPDATE imports
SET status = 'published',
    report = $1::jsonb,
    published_at = now()
WHERE id = $2::uuid
`

type MarkImportPublishedParams struct {
	Report []byte      `json:"report"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) MarkImportPublished(ctx context.Context, arg MarkImportPublishedParams) error {
	_, err := q.db.Exec(ctx, markImportPublished, arg.Report, arg.ID)
	return err
}

const markImportValidated = `-- name: MarkImportValidated :exec
UPDATE imports
SET status = 'validated',
    valid_count = $1::integer,
    invalid_count = $2::integer,
    report = $3::jsonb,
    validated_at = now()
WHERE id = $4::uuid
`

type MarkImportValidatedParams struct {
	ValidCount   int32       `json:"valid_count"`
	InvalidCount int32       `json:"invalid_count"`
	Report       []byte      `json:"report"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) MarkImportValidated(ctx context.Context, arg MarkImportValidatedParams) error {
	_, err := q.db.Exec(ctx, markImportValidated,
		arg.ValidCount,
		arg.InvalidCount,
		arg.Report,
		arg.ID,
	)
	return err
}

const setImportRowStatus = `-- name: SetImportRowStatus :exec
UPDATE import_rows
SET valid = $1::boolean, error = $2::text
WHERE import_id = $3::uuid AND line_number = $4::integer
`

type SetImportRowStatusParams struct {
	Valid      bool        `json:"valid"`
	Error      *string     `json:"error"`
	ImportID   pgtype.UUID `json:"import_id"`
	LineNumber int32       `json:"line_number"`
}

func (q *Queries) SetImportRowStatus(ctx context.Context, arg SetImportRowStatusParams) error {
	_, err := q.db.Exec(ctx, setImportRowStatus,
		arg.Valid,
		arg.Error,
		arg.ImportID,
		arg.LineNumber,
	)
	return err
}
