// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type HousingTransaction string

const (
	HousingTransactionRent HousingTransaction = "rent"
	HousingTransactionSale HousingTransaction = "sale"
)

func (e *HousingTransaction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HousingTransaction(s)
	case string:
		*e = HousingTransaction(s)
	default:
		return fmt.Errorf("unsupported scan type for HousingTransaction: %T", src)
	}
	return nil
}

type NullHousingTransaction struct {
	HousingTransaction HousingTransaction `json:"housing_transaction"`
	Valid              bool               `json:"valid"` // Valid is true if HousingTransaction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHousingTransaction) Scan(value interface{}) error {
	if value == nil {
		ns.HousingTransaction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HousingTransaction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHousingTransaction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HousingTransaction), nil
}

type IncomeBasis string

const (
	IncomeBasisGross IncomeBasis = "gross"
	IncomeBasisNet   IncomeBasis = "net"
)

func (e *IncomeBasis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncomeBasis(s)
	case string:
		*e = IncomeBasis(s)
	default:
		return fmt.Errorf("unsupported scan type for IncomeBasis: %T", src)
	}
	return nil
}

type NullIncomeBasis struct {
	IncomeBasis IncomeBasis `json:"income_basis"`
	Valid       bool        `json:"valid"` // Valid is true if IncomeBasis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncomeBasis) Scan(value interface{}) error {
	if value == nil {
		ns.IncomeBasis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncomeBasis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncomeBasis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncomeBasis), nil
}

type IncomePeriod string

const (
	IncomePeriodMonthly IncomePeriod = "monthly"
	IncomePeriodAnnual  IncomePeriod = "annual"
)

func (e *IncomePeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncomePeriod(s)
	case string:
		*e = IncomePeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for IncomePeriod: %T", src)
	}
	return nil
}

type NullIncomePeriod struct {
	IncomePeriod IncomePeriod `json:"income_period"`
	Valid        bool         `json:"valid"` // Valid is true if IncomePeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncomePeriod) Scan(value interface{}) error {
	if value == nil {
		ns.IncomePeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncomePeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncomePeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncomePeriod), nil
}

type ModerationStatus string

const (
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusRejected ModerationStatus = "rejected"
	ModerationStatusFlagged  ModerationStatus = "flagged"
)

func (e *ModerationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationStatus(s)
	case string:
		*e = ModerationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationStatus: %T", src)
	}
	return nil
}

type NullModerationStatus struct {
	ModerationStatus ModerationStatus `json:"moderation_status"`
	Valid            bool             `json:"valid"` // Valid is true if ModerationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationStatus), nil
}

type SourceKind string

const (
	SourceKindCommunity SourceKind = "community"
	SourceKindOfficial  SourceKind = "official"
	SourceKindPartner   SourceKind = "partner"
)

func (e *SourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceKind(s)
	case string:
		*e = SourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceKind: %T", src)
	}
	return nil
}

type NullSourceKind struct {
	SourceKind SourceKind `json:"source_kind"`
	Valid      bool       `json:"valid"` // Valid is true if SourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.SourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceKind), nil
}

type UserRole string

const (
	UserRoleMember    UserRole = "member"
	UserRoleModerator UserRole = "moderator"
	UserRoleAdmin     UserRole = "admin"
	UserRolePartner   UserRole = "partner"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Slug     string      `json:"slug"`
	NameI18n []byte      `json:"name_i18n"`
}

type EvidenceFile struct {
	ID              pgtype.UUID        `json:"id"`
	ObservationType string             `json:"observation_type"`
	ObservationID   pgtype.UUID        `json:"observation_id"`
	ObjectKey       string             `json:"object_key"`
	MediaType       string             `json:"media_type"`
	Sha256          string             `json:"sha256"`
	UploadedBy      pgtype.UUID        `json:"uploaded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FuelPriceObservation struct {
	ID              pgtype.UUID        `json:"id"`
	FuelTypeID      pgtype.UUID        `json:"fuel_type_id"`
	LocationID      pgtype.UUID        `json:"location_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	ContributorID   pgtype.UUID        `json:"contributor_id"`
	AmountPerLitre  pgtype.Numeric     `json:"amount_per_litre"`
	Currency        string             `json:"currency"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID  *string            `json:"source_record_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FuelType struct {
	ID       pgtype.UUID `json:"id"`
	Code     string      `json:"code"`
	NameI18n []byte      `json:"name_i18n"`
	Energy   string      `json:"energy"`
}

type GeoArea struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Type        string      `json:"type"`
	Code        *string     `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Geometry    interface{} `json:"geometry"`
	Centroid    interface{} `json:"centroid"`
}

type HousingObservation struct {
	ID              pgtype.UUID        `json:"id"`
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	TransactionType HousingTransaction `json:"transaction_type"`
	PropertyType    string             `json:"property_type"`
	Rooms           *int16             `json:"rooms"`
	Furnished       *bool              `json:"furnished"`
	Amount          pgtype.Numeric     `json:"amount"`
	AmountPerSqm    pgtype.Numeric     `json:"amount_per_sqm"`
	Currency        string             `json:"currency"`
	SurfaceSqm      pgtype.Numeric     `json:"surface_sqm"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	SourceRecordID  *string            `json:"source_record_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Import struct {
	ID           pgtype.UUID        `json:"id"`
	ResourceType string             `json:"resource_type"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	LineCount    int32              `json:"line_count"`
	ValidCount   int32              `json:"valid_count"`
	InvalidCount int32              `json:"invalid_count"`
	Report       []byte             `json:"report"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ValidatedAt  pgtype.Timestamptz `json:"validated_at"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

type ImportRow struct {
	ID         pgtype.UUID        `json:"id"`
	ImportID   pgtype.UUID        `json:"import_id"`
	LineNumber int32              `json:"line_number"`
	Payload    []byte             `json:"payload"`
	Valid      *bool              `json:"valid"`
	Error      *string            `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type IncomeObservation struct {
	ID             pgtype.UUID        `json:"id"`
	GeoAreaID      pgtype.UUID        `json:"geo_area_id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	OccupationCode *string            `json:"occupation_code"`
	IndustryCode   *string            `json:"industry_code"`
	Amount         pgtype.Numeric     `json:"amount"`
	Currency       string             `json:"currency"`
	Period         IncomePeriod       `json:"period"`
	Basis          IncomeBasis        `json:"basis"`
	Statistic      string             `json:"statistic"`
	SampleSize     *int32             `json:"sample_size"`
	PeriodStart    pgtype.Date        `json:"period_start"`
	PeriodEnd      pgtype.Date        `json:"period_end"`
	Status         ModerationStatus   `json:"status"`
	SourceRecordID *string            `json:"source_record_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Location struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	GeoAreaID   pgtype.UUID        `json:"geo_area_id"`
	Name        string             `json:"name"`
	Address     *string            `json:"address"`
	Position    interface{}        `json:"position"`
	ExternalRef *string            `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	WebsiteUrl *string            `json:"website_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ModerationEvent struct {
	ID              pgtype.UUID        `json:"id"`
	ObservationType string             `json:"observation_type"`
	ObservationID   pgtype.UUID        `json:"observation_id"`
	ModeratorID     pgtype.UUID        `json:"moderator_id"`
	PreviousStatus  *ModerationStatus  `json:"previous_status"`
	NewStatus       ModerationStatus   `json:"new_status"`
	ReasonCode      *string            `json:"reason_code"`
	Note            *string            `json:"note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PriceAggregatesMonthly struct {
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	MetricType      string             `json:"metric_type"`
	SubjectID       pgtype.UUID        `json:"subject_id"`
	Month           pgtype.Date        `json:"month"`
	MedianAmount    pgtype.Numeric     `json:"median_amount"`
	MinAmount       pgtype.Numeric     `json:"min_amount"`
	MaxAmount       pgtype.Numeric     `json:"max_amount"`
	SampleSize      int32              `json:"sample_size"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	CalculatedAt    pgtype.Timestamptz `json:"calculated_at"`
}

type Product struct {
	ID                pgtype.UUID        `json:"id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	Name              string             `json:"name"`
	Brand             *string            `json:"brand"`
	Barcode           *string            `json:"barcode"`
	ReferenceUnitCode string             `json:"reference_unit_code"`
	IsGeneric         bool               `json:"is_generic"`
	Attributes        []byte             `json:"attributes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProductPriceObservation struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   *string            `json:"source_record_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	UserAgent        *string            `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
}

type Source struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Kind        SourceKind         `json:"kind"`
	HomepageUrl *string            `json:"homepage_url"`
	LicenseName *string            `json:"license_name"`
	LicenseUrl  *string            `json:"license_url"`
	Attribution *string            `json:"attribution"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Unit struct {
	Code         string         `json:"code"`
	Dimension    string         `json:"dimension"`
	ToBaseFactor pgtype.Numeric `json:"to_base_factor"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    *string            `json:"password_hash"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
