// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listModerationQueue = `-- name: ListModerationQueue :many
SELECT
    id,
    observation_type,
    status,
    subject,
    contributor_id,
    contributor_email,
    amount,
    currency,
    quantity,
    unit_code,
    is_promotion,
    location_id,
    location_name,
    geo_area_id,
    geo_area_name,
    source_id,
    source_name,
    source_kind,
    observed_at,
    confidence_score,
    created_at
FROM (
    SELECT
        o.id AS id,
        'fuel_price'::text AS observation_type,
        o.status AS status,
        f.name_i18n->>'fr' AS subject,
        o.contributor_id AS contributor_id,
        u.email AS contributor_email,
        o.amount_per_litre::text AS amount,
        o.currency AS currency,
        NULL::text AS quantity,
        NULL::varchar AS unit_code,
        NULL::boolean AS is_promotion,
        o.location_id AS location_id,
        l.name AS location_name,
        g.id AS geo_area_id,
        g.name AS geo_area_name,
        s.id AS source_id,
        s.name AS source_name,
        s.kind AS source_kind,
        o.observed_at AS observed_at,
        o.confidence_score AS confidence_score,
        o.created_at AS created_at
    FROM fuel_price_observations AS o
    JOIN fuel_types AS f ON f.id = o.fuel_type_id
    JOIN locations AS l ON l.id = o.location_id
    JOIN geo_areas AS g ON g.id = l.geo_area_id
    JOIN sources AS s ON s.id = o.source_id
    LEFT JOIN users AS u ON u.id = o.contributor_id
    UNION ALL
    SELECT
        o.id AS id,
        'product_price'::text AS observation_type,
        o.status AS status,
        p.name AS subject,
        o.contributor_id AS contributor_id,
        u.email AS contributor_email,
        o.amount::text AS amount,
        o.currency AS currency,
        o.quantity::text AS quantity,
        o.unit_code AS unit_code,
        o.is_promotion AS is_promotion,
        o.location_id AS location_id,
        l.name AS location_name,
        g.id AS geo_area_id,
        g.name AS geo_area_name,
        s.id AS source_id,
        s.name AS source_name,
        s.kind AS source_kind,
        o.observed_at AS observed_at,
        o.confidence_score AS confidence_score,
        o.created_at AS created_at
    FROM product_price_observations AS o
    JOIN products AS p ON p.id = o.product_id
    JOIN locations AS l ON l.id = o.location_id
    JOIN geo_areas AS g ON g.id = l.geo_area_id
    JOIN sources AS s ON s.id = o.source_id
    LEFT JOIN users AS u ON u.id = o.contributor_id
) AS queue
WHERE ($1::text IS NULL OR queue.status::text = $1::text)
ORDER BY queue.created_at DESC, queue.id
LIMIT $3::integer OFFSET $2::integer
`

type ListModerationQueueParams struct {
	Status     *string `json:"status"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

type ListModerationQueueRow struct {
	ID               pgtype.UUID        `json:"id"`
	ObservationType  string             `json:"observation_type"`
	Status           ModerationStatus   `json:"status"`
	Subject          interface{}        `json:"subject"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	ContributorEmail *string            `json:"contributor_email"`
	Amount           string             `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         *string            `json:"quantity"`
	UnitCode         *string            `json:"unit_code"`
	IsPromotion      *bool              `json:"is_promotion"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListModerationQueue(ctx context.Context, arg ListModerationQueueParams) ([]ListModerationQueueRow, error) {
	rows, err := q.db.Query(ctx, listModerationQueue, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationQueueRow{}
	for rows.Next() {
		var i ListModerationQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.ObservationType,
			&i.Status,
			&i.Subject,
			&i.ContributorID,
			&i.ContributorEmail,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitCode,
			&i.IsPromotion,
			&i.LocationID,
			&i.LocationName,
			&i.GeoAreaID,
			&i.GeoAreaName,
			&i.SourceID,
			&i.SourceName,
			&i.SourceKind,
			&i.ObservedAt,
			&i.ConfidenceScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFuelContributionStatus = `-- name: SetFuelContributionStatus :execrows
UPDATE fuel_price_observations
SET status = $1::moderation_status
WHERE id = $2::uuid
  AND status IN ('pending', 'flagged')
`

type SetFuelContributionStatusParams struct {
	Status ModerationStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) SetFuelContributionStatus(ctx context.Context, arg SetFuelContributionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFuelContributionStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProductContributionStatus = `-- name: SetProductContributionStatus :execrows
UPDATE product_price_observations
SET status = $1::moderation_status
WHERE id = $2::uuid
  AND status IN ('pending', 'flagged')
`

type SetProductContributionStatusParams struct {
	Status ModerationStatus `json:"status"`
	ID     pgtype.UUID      `json:"id"`
}

func (q *Queries) SetProductContributionStatus(ctx context.Context, arg SetProductContributionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductContributionStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
