// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: observations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendModerationEvent = `-- name: AppendModerationEvent :one
INSERT INTO moderation_events(observation_type,observation_id,moderator_id,previous_status,new_status,reason_code,note)
VALUES($1::varchar,$2::uuid,$3::uuid,
$4::moderation_status,$5::moderation_status,$6::varchar,$7::text) RETURNING id, observation_type, observation_id, moderator_id, previous_status, new_status, reason_code, note, created_at
`

type AppendModerationEventParams struct {
	ObservationType string            `json:"observation_type"`
	ObservationID   pgtype.UUID       `json:"observation_id"`
	ModeratorID     pgtype.UUID       `json:"moderator_id"`
	PreviousStatus  *ModerationStatus `json:"previous_status"`
	NewStatus       ModerationStatus  `json:"new_status"`
	ReasonCode      *string           `json:"reason_code"`
	Note            *string           `json:"note"`
}

func (q *Queries) AppendModerationEvent(ctx context.Context, arg AppendModerationEventParams) (ModerationEvent, error) {
	row := q.db.QueryRow(ctx, appendModerationEvent,
		arg.ObservationType,
		arg.ObservationID,
		arg.ModeratorID,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.ReasonCode,
		arg.Note,
	)
	var i ModerationEvent
	err := row.Scan(
		&i.ID,
		&i.ObservationType,
		&i.ObservationID,
		&i.ModeratorID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.ReasonCode,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvidenceFile = `-- name: DeleteEvidenceFile :execrows
DELETE FROM evidence_files WHERE id=$1::uuid
`

func (q *Queries) DeleteEvidenceFile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvidenceFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFuelPrice = `-- name: DeleteFuelPrice :execrows
DELETE FROM fuel_price_observations WHERE id=$1::uuid
`

func (q *Queries) DeleteFuelPrice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFuelPrice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHousingObservation = `-- name: DeleteHousingObservation :execrows
DELETE FROM housing_observations WHERE id=$1::uuid
`

func (q *Queries) DeleteHousingObservation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHousingObservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIncomeObservation = `-- name: DeleteIncomeObservation :execrows
DELETE FROM income_observations WHERE id=$1::uuid
`

func (q *Queries) DeleteIncomeObservation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIncomeObservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePriceAggregate = `-- name: DeletePriceAggregate :execrows
DELETE FROM price_aggregates_monthly WHERE geo_area_id=$1::uuid AND metric_type=$2::varchar
AND subject_id=$3::uuid AND month=$4::date
`

type DeletePriceAggregateParams struct {
	GeoAreaID  pgtype.UUID `json:"geo_area_id"`
	MetricType string      `json:"metric_type"`
	SubjectID  pgtype.UUID `json:"subject_id"`
	Month      pgtype.Date `json:"month"`
}

func (q *Queries) DeletePriceAggregate(ctx context.Context, arg DeletePriceAggregateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePriceAggregate,
		arg.GeoAreaID,
		arg.MetricType,
		arg.SubjectID,
		arg.Month,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id,email,display_name,role,locale,reputation_score,email_verified_at,created_at,updated_at,deleted_at FROM users WHERE id=$1::uuid
`

type GetAdminUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetAdminUser(ctx context.Context, id pgtype.UUID) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Locale,
		&i.ReputationScore,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEvidenceFile = `-- name: GetEvidenceFile :one
SELECT id, observation_type, observation_id, object_key, media_type, sha256, uploaded_by, created_at FROM evidence_files WHERE id=$1::uuid
`

func (q *Queries) GetEvidenceFile(ctx context.Context, id pgtype.UUID) (EvidenceFile, error) {
	row := q.db.QueryRow(ctx, getEvidenceFile, id)
	var i EvidenceFile
	err := row.Scan(
		&i.ID,
		&i.ObservationType,
		&i.ObservationID,
		&i.ObjectKey,
		&i.MediaType,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getFuelPrice = `-- name: GetFuelPrice :one
SELECT id, fuel_type_id, location_id, source_id, contributor_id, amount_per_litre, currency, observed_at, status, confidence_score, source_record_id, created_at FROM fuel_price_observations WHERE id=$1::uuid
`

func (q *Queries) GetFuelPrice(ctx context.Context, id pgtype.UUID) (FuelPriceObservation, error) {
	row := q.db.QueryRow(ctx, getFuelPrice, id)
	var i FuelPriceObservation
	err := row.Scan(
		&i.ID,
		&i.FuelTypeID,
		&i.LocationID,
		&i.SourceID,
		&i.ContributorID,
		&i.AmountPerLitre,
		&i.Currency,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const getHousingObservation = `-- name: GetHousingObservation :one
SELECT id, geo_area_id, source_id, transaction_type, property_type, rooms, furnished, amount, amount_per_sqm, currency, surface_sqm, observed_at, status, source_record_id, created_at FROM housing_observations WHERE id=$1::uuid
`

func (q *Queries) GetHousingObservation(ctx context.Context, id pgtype.UUID) (HousingObservation, error) {
	row := q.db.QueryRow(ctx, getHousingObservation, id)
	var i HousingObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.TransactionType,
		&i.PropertyType,
		&i.Rooms,
		&i.Furnished,
		&i.Amount,
		&i.AmountPerSqm,
		&i.Currency,
		&i.SurfaceSqm,
		&i.ObservedAt,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const getIncomeObservation = `-- name: GetIncomeObservation :one
SELECT id, geo_area_id, source_id, occupation_code, industry_code, amount, currency, period, basis, statistic, sample_size, period_start, period_end, status, source_record_id, created_at FROM income_observations WHERE id=$1::uuid
`

func (q *Queries) GetIncomeObservation(ctx context.Context, id pgtype.UUID) (IncomeObservation, error) {
	row := q.db.QueryRow(ctx, getIncomeObservation, id)
	var i IncomeObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.OccupationCode,
		&i.IndustryCode,
		&i.Amount,
		&i.Currency,
		&i.Period,
		&i.Basis,
		&i.Statistic,
		&i.SampleSize,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const getModerationEvent = `-- name: GetModerationEvent :one
SELECT id, observation_type, observation_id, moderator_id, previous_status, new_status, reason_code, note, created_at FROM moderation_events WHERE id=$1::uuid
`

func (q *Queries) GetModerationEvent(ctx context.Context, id pgtype.UUID) (ModerationEvent, error) {
	row := q.db.QueryRow(ctx, getModerationEvent, id)
	var i ModerationEvent
	err := row.Scan(
		&i.ID,
		&i.ObservationType,
		&i.ObservationID,
		&i.ModeratorID,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.ReasonCode,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPriceAggregate = `-- name: GetPriceAggregate :one
SELECT geo_area_id, metric_type, subject_id, month, median_amount, min_amount, max_amount, sample_size, confidence_score, calculated_at FROM price_aggregates_monthly WHERE geo_area_id=$1::uuid AND metric_type=$2::varchar
AND subject_id=$3::uuid AND month=$4::date
`

type GetPriceAggregateParams struct {
	GeoAreaID  pgtype.UUID `json:"geo_area_id"`
	MetricType string      `json:"metric_type"`
	SubjectID  pgtype.UUID `json:"subject_id"`
	Month      pgtype.Date `json:"month"`
}

func (q *Queries) GetPriceAggregate(ctx context.Context, arg GetPriceAggregateParams) (PriceAggregatesMonthly, error) {
	row := q.db.QueryRow(ctx, getPriceAggregate,
		arg.GeoAreaID,
		arg.MetricType,
		arg.SubjectID,
		arg.Month,
	)
	var i PriceAggregatesMonthly
	err := row.Scan(
		&i.GeoAreaID,
		&i.MetricType,
		&i.SubjectID,
		&i.Month,
		&i.MedianAmount,
		&i.MinAmount,
		&i.MaxAmount,
		&i.SampleSize,
		&i.ConfidenceScore,
		&i.CalculatedAt,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id,email,display_name,role,locale,reputation_score,email_verified_at,created_at,updated_at,deleted_at
FROM users ORDER BY created_at DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListAdminUsersParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListAdminUsersRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	Role            UserRole           `json:"role"`
	Locale          string             `json:"locale"`
	ReputationScore int32              `json:"reputation_score"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Locale,
			&i.ReputationScore,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceFiles = `-- name: ListEvidenceFiles :many
SELECT id, observation_type, observation_id, object_key, media_type, sha256, uploaded_by, created_at FROM evidence_files ORDER BY created_at DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListEvidenceFilesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListEvidenceFiles(ctx context.Context, arg ListEvidenceFilesParams) ([]EvidenceFile, error) {
	rows, err := q.db.Query(ctx, listEvidenceFiles, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvidenceFile{}
	for rows.Next() {
		var i EvidenceFile
		if err := rows.Scan(
			&i.ID,
			&i.ObservationType,
			&i.ObservationID,
			&i.ObjectKey,
			&i.MediaType,
			&i.Sha256,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelPrices = `-- name: ListFuelPrices :many
SELECT id, fuel_type_id, location_id, source_id, contributor_id, amount_per_litre, currency, observed_at, status, confidence_score, source_record_id, created_at FROM fuel_price_observations ORDER BY observed_at DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListFuelPricesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListFuelPrices(ctx context.Context, arg ListFuelPricesParams) ([]FuelPriceObservation, error) {
	rows, err := q.db.Query(ctx, listFuelPrices, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelPriceObservation{}
	for rows.Next() {
		var i FuelPriceObservation
		if err := rows.Scan(
			&i.ID,
			&i.FuelTypeID,
			&i.LocationID,
			&i.SourceID,
			&i.ContributorID,
			&i.AmountPerLitre,
			&i.Currency,
			&i.ObservedAt,
			&i.Status,
			&i.ConfidenceScore,
			&i.SourceRecordID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHousingObservations = `-- name: ListHousingObservations :many
SELECT id, geo_area_id, source_id, transaction_type, property_type, rooms, furnished, amount, amount_per_sqm, currency, surface_sqm, observed_at, status, source_record_id, created_at FROM housing_observations ORDER BY observed_at DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListHousingObservationsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListHousingObservations(ctx context.Context, arg ListHousingObservationsParams) ([]HousingObservation, error) {
	rows, err := q.db.Query(ctx, listHousingObservations, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HousingObservation{}
	for rows.Next() {
		var i HousingObservation
		if err := rows.Scan(
			&i.ID,
			&i.GeoAreaID,
			&i.SourceID,
			&i.TransactionType,
			&i.PropertyType,
			&i.Rooms,
			&i.Furnished,
			&i.Amount,
			&i.AmountPerSqm,
			&i.Currency,
			&i.SurfaceSqm,
			&i.ObservedAt,
			&i.Status,
			&i.SourceRecordID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeObservations = `-- name: ListIncomeObservations :many
SELECT id, geo_area_id, source_id, occupation_code, industry_code, amount, currency, period, basis, statistic, sample_size, period_start, period_end, status, source_record_id, created_at FROM income_observations ORDER BY period_end DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListIncomeObservationsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListIncomeObservations(ctx context.Context, arg ListIncomeObservationsParams) ([]IncomeObservation, error) {
	rows, err := q.db.Query(ctx, listIncomeObservations, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncomeObservation{}
	for rows.Next() {
		var i IncomeObservation
		if err := rows.Scan(
			&i.ID,
			&i.GeoAreaID,
			&i.SourceID,
			&i.OccupationCode,
			&i.IndustryCode,
			&i.Amount,
			&i.Currency,
			&i.Period,
			&i.Basis,
			&i.Statistic,
			&i.SampleSize,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.SourceRecordID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationEvents = `-- name: ListModerationEvents :many
SELECT id, observation_type, observation_id, moderator_id, previous_status, new_status, reason_code, note, created_at FROM moderation_events ORDER BY created_at DESC,id LIMIT $2::integer OFFSET $1::integer
`

type ListModerationEventsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListModerationEvents(ctx context.Context, arg ListModerationEventsParams) ([]ModerationEvent, error) {
	rows, err := q.db.Query(ctx, listModerationEvents, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationEvent{}
	for rows.Next() {
		var i ModerationEvent
		if err := rows.Scan(
			&i.ID,
			&i.ObservationType,
			&i.ObservationID,
			&i.ModeratorID,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.ReasonCode,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceAggregates = `-- name: ListPriceAggregates :many
SELECT geo_area_id, metric_type, subject_id, month, median_amount, min_amount, max_amount, sample_size, confidence_score, calculated_at FROM price_aggregates_monthly ORDER BY month DESC,geo_area_id,metric_type,subject_id LIMIT $2::integer OFFSET $1::integer
`

type ListPriceAggregatesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListPriceAggregates(ctx context.Context, arg ListPriceAggregatesParams) ([]PriceAggregatesMonthly, error) {
	rows, err := q.db.Query(ctx, listPriceAggregates, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAggregatesMonthly{}
	for rows.Next() {
		var i PriceAggregatesMonthly
		if err := rows.Scan(
			&i.GeoAreaID,
			&i.MetricType,
			&i.SubjectID,
			&i.Month,
			&i.MedianAmount,
			&i.MinAmount,
			&i.MaxAmount,
			&i.SampleSize,
			&i.ConfidenceScore,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvidenceByID = `-- name: UpsertEvidenceByID :one
INSERT INTO evidence_files(id,observation_type,observation_id,object_key,media_type,sha256,uploaded_by)
VALUES($1::uuid,$2::varchar,$3::uuid,$4::text,
$5::text,$6::char(64),$7::uuid)
ON CONFLICT(id) DO UPDATE SET observation_type=EXCLUDED.observation_type,observation_id=EXCLUDED.observation_id,object_key=EXCLUDED.object_key,
media_type=EXCLUDED.media_type,sha256=EXCLUDED.sha256,uploaded_by=EXCLUDED.uploaded_by RETURNING id, observation_type, observation_id, object_key, media_type, sha256, uploaded_by, created_at
`

type UpsertEvidenceByIDParams struct {
	ID              pgtype.UUID `json:"id"`
	ObservationType string      `json:"observation_type"`
	ObservationID   pgtype.UUID `json:"observation_id"`
	ObjectKey       string      `json:"object_key"`
	MediaType       string      `json:"media_type"`
	Sha256          string      `json:"sha256"`
	UploadedBy      pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) UpsertEvidenceByID(ctx context.Context, arg UpsertEvidenceByIDParams) (EvidenceFile, error) {
	row := q.db.QueryRow(ctx, upsertEvidenceByID,
		arg.ID,
		arg.ObservationType,
		arg.ObservationID,
		arg.ObjectKey,
		arg.MediaType,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i EvidenceFile
	err := row.Scan(
		&i.ID,
		&i.ObservationType,
		&i.ObservationID,
		&i.ObjectKey,
		&i.MediaType,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEvidenceByObjectKey = `-- name: UpsertEvidenceByObjectKey :one
INSERT INTO evidence_files (
    observation_type, observation_id, object_key, media_type, sha256, uploaded_by
) VALUES (
    $1::varchar,
    $2::uuid,
    $3::text,
    $4::text,
    $5::char(64),
    $6::uuid
)
ON CONFLICT (object_key) DO UPDATE SET
    observation_type = EXCLUDED.observation_type,
    observation_id = EXCLUDED.observation_id,
    media_type = EXCLUDED.media_type,
    sha256 = EXCLUDED.sha256,
    uploaded_by = EXCLUDED.uploaded_by
RETURNING id, observation_type, observation_id, object_key, media_type, sha256, uploaded_by, created_at
`

type UpsertEvidenceByObjectKeyParams struct {
	ObservationType string      `json:"observation_type"`
	ObservationID   pgtype.UUID `json:"observation_id"`
	ObjectKey       string      `json:"object_key"`
	MediaType       string      `json:"media_type"`
	Sha256          string      `json:"sha256"`
	UploadedBy      pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) UpsertEvidenceByObjectKey(ctx context.Context, arg UpsertEvidenceByObjectKeyParams) (EvidenceFile, error) {
	row := q.db.QueryRow(ctx, upsertEvidenceByObjectKey,
		arg.ObservationType,
		arg.ObservationID,
		arg.ObjectKey,
		arg.MediaType,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i EvidenceFile
	err := row.Scan(
		&i.ID,
		&i.ObservationType,
		&i.ObservationID,
		&i.ObjectKey,
		&i.MediaType,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFuelPriceByID = `-- name: UpsertFuelPriceByID :one
INSERT INTO fuel_price_observations(id,fuel_type_id,location_id,source_id,contributor_id,amount_per_litre,currency,observed_at,status,confidence_score,source_record_id)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,
$6::numeric,$7::char(3),$8::timestamptz,$9::moderation_status,
$10::numeric,$11::text)
ON CONFLICT(id) DO UPDATE SET fuel_type_id=EXCLUDED.fuel_type_id,location_id=EXCLUDED.location_id,source_id=EXCLUDED.source_id,
contributor_id=EXCLUDED.contributor_id,amount_per_litre=EXCLUDED.amount_per_litre,currency=EXCLUDED.currency,observed_at=EXCLUDED.observed_at,
status=EXCLUDED.status,confidence_score=EXCLUDED.confidence_score,source_record_id=EXCLUDED.source_record_id RETURNING id, fuel_type_id, location_id, source_id, contributor_id, amount_per_litre, currency, observed_at, status, confidence_score, source_record_id, created_at
`

type UpsertFuelPriceByIDParams struct {
	ID              pgtype.UUID        `json:"id"`
	FuelTypeID      pgtype.UUID        `json:"fuel_type_id"`
	LocationID      pgtype.UUID        `json:"location_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	ContributorID   pgtype.UUID        `json:"contributor_id"`
	AmountPerLitre  pgtype.Numeric     `json:"amount_per_litre"`
	Currency        string             `json:"currency"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID  *string            `json:"source_record_id"`
}

func (q *Queries) UpsertFuelPriceByID(ctx context.Context, arg UpsertFuelPriceByIDParams) (FuelPriceObservation, error) {
	row := q.db.QueryRow(ctx, upsertFuelPriceByID,
		arg.ID,
		arg.FuelTypeID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.AmountPerLitre,
		arg.Currency,
		arg.ObservedAt,
		arg.Status,
		arg.ConfidenceScore,
		arg.SourceRecordID,
	)
	var i FuelPriceObservation
	err := row.Scan(
		&i.ID,
		&i.FuelTypeID,
		&i.LocationID,
		&i.SourceID,
		&i.ContributorID,
		&i.AmountPerLitre,
		&i.Currency,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFuelPriceBySourceRecord = `-- name: UpsertFuelPriceBySourceRecord :one
INSERT INTO fuel_price_observations (
    fuel_type_id,
    location_id,
    source_id,
    contributor_id,
    amount_per_litre,
    currency,
    observed_at,
    status,
    confidence_score,
    source_record_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::numeric,
    $6::char(3),
    $7::timestamptz,
    $8::moderation_status,
    $9::numeric,
    $10::text
)
ON CONFLICT (source_id, source_record_id) WHERE source_record_id IS NOT NULL DO UPDATE SET
    fuel_type_id = EXCLUDED.fuel_type_id,
    location_id = EXCLUDED.location_id,
    contributor_id = EXCLUDED.contributor_id,
    amount_per_litre = EXCLUDED.amount_per_litre,
    currency = EXCLUDED.currency,
    observed_at = EXCLUDED.observed_at,
    status = EXCLUDED.status,
    confidence_score = EXCLUDED.confidence_score
RETURNING id, fuel_type_id, location_id, source_id, contributor_id, amount_per_litre, currency, observed_at, status, confidence_score, source_record_id, created_at
`

type UpsertFuelPriceBySourceRecordParams struct {
	FuelTypeID      pgtype.UUID        `json:"fuel_type_id"`
	LocationID      pgtype.UUID        `json:"location_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	ContributorID   pgtype.UUID        `json:"contributor_id"`
	AmountPerLitre  pgtype.Numeric     `json:"amount_per_litre"`
	Currency        string             `json:"currency"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID  string             `json:"source_record_id"`
}

func (q *Queries) UpsertFuelPriceBySourceRecord(ctx context.Context, arg UpsertFuelPriceBySourceRecordParams) (FuelPriceObservation, error) {
	row := q.db.QueryRow(ctx, upsertFuelPriceBySourceRecord,
		arg.FuelTypeID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.AmountPerLitre,
		arg.Currency,
		arg.ObservedAt,
		arg.Status,
		arg.ConfidenceScore,
		arg.SourceRecordID,
	)
	var i FuelPriceObservation
	err := row.Scan(
		&i.ID,
		&i.FuelTypeID,
		&i.LocationID,
		&i.SourceID,
		&i.ContributorID,
		&i.AmountPerLitre,
		&i.Currency,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHousingByID = `-- name: UpsertHousingByID :one
INSERT INTO housing_observations(id,geo_area_id,source_id,transaction_type,property_type,rooms,furnished,amount,amount_per_sqm,currency,surface_sqm,observed_at,status,source_record_id)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::housing_transaction,
$5::varchar,$6::smallint,$7::boolean,$8::numeric,
$9::numeric,$10::char(3),$11::numeric,$12::timestamptz,
$13::moderation_status,$14::text)
ON CONFLICT(id) DO UPDATE SET geo_area_id=EXCLUDED.geo_area_id,source_id=EXCLUDED.source_id,transaction_type=EXCLUDED.transaction_type,
property_type=EXCLUDED.property_type,rooms=EXCLUDED.rooms,furnished=EXCLUDED.furnished,amount=EXCLUDED.amount,amount_per_sqm=EXCLUDED.amount_per_sqm,
currency=EXCLUDED.currency,surface_sqm=EXCLUDED.surface_sqm,observed_at=EXCLUDED.observed_at,status=EXCLUDED.status,source_record_id=EXCLUDED.source_record_id RETURNING id, geo_area_id, source_id, transaction_type, property_type, rooms, furnished, amount, amount_per_sqm, currency, surface_sqm, observed_at, status, source_record_id, created_at
`

type UpsertHousingByIDParams struct {
	ID              pgtype.UUID        `json:"id"`
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	TransactionType HousingTransaction `json:"transaction_type"`
	PropertyType    string             `json:"property_type"`
	Rooms           *int16             `json:"rooms"`
	Furnished       *bool              `json:"furnished"`
	Amount          pgtype.Numeric     `json:"amount"`
	AmountPerSqm    pgtype.Numeric     `json:"amount_per_sqm"`
	Currency        string             `json:"currency"`
	SurfaceSqm      pgtype.Numeric     `json:"surface_sqm"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	SourceRecordID  *string            `json:"source_record_id"`
}

func (q *Queries) UpsertHousingByID(ctx context.Context, arg UpsertHousingByIDParams) (HousingObservation, error) {
	row := q.db.QueryRow(ctx, upsertHousingByID,
		arg.ID,
		arg.GeoAreaID,
		arg.SourceID,
		arg.TransactionType,
		arg.PropertyType,
		arg.Rooms,
		arg.Furnished,
		arg.Amount,
		arg.AmountPerSqm,
		arg.Currency,
		arg.SurfaceSqm,
		arg.ObservedAt,
		arg.Status,
		arg.SourceRecordID,
	)
	var i HousingObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.TransactionType,
		&i.PropertyType,
		&i.Rooms,
		&i.Furnished,
		&i.Amount,
		&i.AmountPerSqm,
		&i.Currency,
		&i.SurfaceSqm,
		&i.ObservedAt,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHousingBySourceRecord = `-- name: UpsertHousingBySourceRecord :one
INSERT INTO housing_observations (
    geo_area_id,
    source_id,
    transaction_type,
    property_type,
    rooms,
    furnished,
    amount,
    amount_per_sqm,
    currency,
    surface_sqm,
    observed_at,
    status,
    source_record_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::housing_transaction,
    $4::varchar,
    $5::smallint,
    $6::boolean,
    $7::numeric,
    $8::numeric,
    $9::char(3),
    $10::numeric,
    $11::timestamptz,
    $12::moderation_status,
    $13::text
)
ON CONFLICT (source_id, source_record_id) WHERE source_record_id IS NOT NULL DO UPDATE SET
    geo_area_id = EXCLUDED.geo_area_id,
    transaction_type = EXCLUDED.transaction_type,
    property_type = EXCLUDED.property_type,
    rooms = EXCLUDED.rooms,
    furnished = EXCLUDED.furnished,
    amount = EXCLUDED.amount,
    amount_per_sqm = EXCLUDED.amount_per_sqm,
    currency = EXCLUDED.currency,
    surface_sqm = EXCLUDED.surface_sqm,
    observed_at = EXCLUDED.observed_at,
    status = EXCLUDED.status
RETURNING id, geo_area_id, source_id, transaction_type, property_type, rooms, furnished, amount, amount_per_sqm, currency, surface_sqm, observed_at, status, source_record_id, created_at
`

type UpsertHousingBySourceRecordParams struct {
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	SourceID        pgtype.UUID        `json:"source_id"`
	TransactionType HousingTransaction `json:"transaction_type"`
	PropertyType    string             `json:"property_type"`
	Rooms           *int16             `json:"rooms"`
	Furnished       *bool              `json:"furnished"`
	Amount          pgtype.Numeric     `json:"amount"`
	AmountPerSqm    pgtype.Numeric     `json:"amount_per_sqm"`
	Currency        string             `json:"currency"`
	SurfaceSqm      pgtype.Numeric     `json:"surface_sqm"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	Status          ModerationStatus   `json:"status"`
	SourceRecordID  string             `json:"source_record_id"`
}

func (q *Queries) UpsertHousingBySourceRecord(ctx context.Context, arg UpsertHousingBySourceRecordParams) (HousingObservation, error) {
	row := q.db.QueryRow(ctx, upsertHousingBySourceRecord,
		arg.GeoAreaID,
		arg.SourceID,
		arg.TransactionType,
		arg.PropertyType,
		arg.Rooms,
		arg.Furnished,
		arg.Amount,
		arg.AmountPerSqm,
		arg.Currency,
		arg.SurfaceSqm,
		arg.ObservedAt,
		arg.Status,
		arg.SourceRecordID,
	)
	var i HousingObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.TransactionType,
		&i.PropertyType,
		&i.Rooms,
		&i.Furnished,
		&i.Amount,
		&i.AmountPerSqm,
		&i.Currency,
		&i.SurfaceSqm,
		&i.ObservedAt,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertIncomeByID = `-- name: UpsertIncomeByID :one
INSERT INTO income_observations(id,geo_area_id,source_id,occupation_code,industry_code,amount,currency,period,basis,statistic,sample_size,period_start,period_end,status,source_record_id)
VALUES($1::uuid,$2::uuid,$3::uuid,$4::varchar,
$5::varchar,$6::numeric,$7::char(3),$8::income_period,
$9::income_basis,$10::varchar,$11::integer,$12::date,
$13::date,$14::moderation_status,$15::text)
ON CONFLICT(id) DO UPDATE SET geo_area_id=EXCLUDED.geo_area_id,source_id=EXCLUDED.source_id,occupation_code=EXCLUDED.occupation_code,
industry_code=EXCLUDED.industry_code,amount=EXCLUDED.amount,currency=EXCLUDED.currency,period=EXCLUDED.period,basis=EXCLUDED.basis,
statistic=EXCLUDED.statistic,sample_size=EXCLUDED.sample_size,period_start=EXCLUDED.period_start,period_end=EXCLUDED.period_end,
status=EXCLUDED.status,source_record_id=EXCLUDED.source_record_id RETURNING id, geo_area_id, source_id, occupation_code, industry_code, amount, currency, period, basis, statistic, sample_size, period_start, period_end, status, source_record_id, created_at
`

type UpsertIncomeByIDParams struct {
	ID             pgtype.UUID      `json:"id"`
	GeoAreaID      pgtype.UUID      `json:"geo_area_id"`
	SourceID       pgtype.UUID      `json:"source_id"`
	OccupationCode *string          `json:"occupation_code"`
	IndustryCode   *string          `json:"industry_code"`
	Amount         pgtype.Numeric   `json:"amount"`
	Currency       string           `json:"currency"`
	Period         IncomePeriod     `json:"period"`
	Basis          IncomeBasis      `json:"basis"`
	Statistic      string           `json:"statistic"`
	SampleSize     *int32           `json:"sample_size"`
	PeriodStart    pgtype.Date      `json:"period_start"`
	PeriodEnd      pgtype.Date      `json:"period_end"`
	Status         ModerationStatus `json:"status"`
	SourceRecordID *string          `json:"source_record_id"`
}

func (q *Queries) UpsertIncomeByID(ctx context.Context, arg UpsertIncomeByIDParams) (IncomeObservation, error) {
	row := q.db.QueryRow(ctx, upsertIncomeByID,
		arg.ID,
		arg.GeoAreaID,
		arg.SourceID,
		arg.OccupationCode,
		arg.IndustryCode,
		arg.Amount,
		arg.Currency,
		arg.Period,
		arg.Basis,
		arg.Statistic,
		arg.SampleSize,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.SourceRecordID,
	)
	var i IncomeObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.OccupationCode,
		&i.IndustryCode,
		&i.Amount,
		&i.Currency,
		&i.Period,
		&i.Basis,
		&i.Statistic,
		&i.SampleSize,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertIncomeBySourceRecord = `-- name: UpsertIncomeBySourceRecord :one
INSERT INTO income_observations (
    geo_area_id,
    source_id,
    occupation_code,
    industry_code,
    amount,
    currency,
    period,
    basis,
    statistic,
    sample_size,
    period_start,
    period_end,
    status,
    source_record_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::numeric,
    $6::char(3),
    $7::income_period,
    $8::income_basis,
    $9::varchar,
    $10::integer,
    $11::date,
    $12::date,
    $13::moderation_status,
    $14::text
)
ON CONFLICT (source_id, source_record_id) WHERE source_record_id IS NOT NULL DO UPDATE SET
    geo_area_id = EXCLUDED.geo_area_id,
    occupation_code = EXCLUDED.occupation_code,
    industry_code = EXCLUDED.industry_code,
    amount = EXCLUDED.amount,
    currency = EXCLUDED.currency,
    period = EXCLUDED.period,
    basis = EXCLUDED.basis,
    statistic = EXCLUDED.statistic,
    sample_size = EXCLUDED.sample_size,
    period_start = EXCLUDED.period_start,
    period_end = EXCLUDED.period_end,
    status = EXCLUDED.status
RETURNING id, geo_area_id, source_id, occupation_code, industry_code, amount, currency, period, basis, statistic, sample_size, period_start, period_end, status, source_record_id, created_at
`

type UpsertIncomeBySourceRecordParams struct {
	GeoAreaID      pgtype.UUID      `json:"geo_area_id"`
	SourceID       pgtype.UUID      `json:"source_id"`
	OccupationCode *string          `json:"occupation_code"`
	IndustryCode   *string          `json:"industry_code"`
	Amount         pgtype.Numeric   `json:"amount"`
	Currency       string           `json:"currency"`
	Period         IncomePeriod     `json:"period"`
	Basis          IncomeBasis      `json:"basis"`
	Statistic      string           `json:"statistic"`
	SampleSize     *int32           `json:"sample_size"`
	PeriodStart    pgtype.Date      `json:"period_start"`
	PeriodEnd      pgtype.Date      `json:"period_end"`
	Status         ModerationStatus `json:"status"`
	SourceRecordID string           `json:"source_record_id"`
}

func (q *Queries) UpsertIncomeBySourceRecord(ctx context.Context, arg UpsertIncomeBySourceRecordParams) (IncomeObservation, error) {
	row := q.db.QueryRow(ctx, upsertIncomeBySourceRecord,
		arg.GeoAreaID,
		arg.SourceID,
		arg.OccupationCode,
		arg.IndustryCode,
		arg.Amount,
		arg.Currency,
		arg.Period,
		arg.Basis,
		arg.Statistic,
		arg.SampleSize,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.SourceRecordID,
	)
	var i IncomeObservation
	err := row.Scan(
		&i.ID,
		&i.GeoAreaID,
		&i.SourceID,
		&i.OccupationCode,
		&i.IndustryCode,
		&i.Amount,
		&i.Currency,
		&i.Period,
		&i.Basis,
		&i.Statistic,
		&i.SampleSize,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMonthlyPriceAggregate = `-- name: UpsertMonthlyPriceAggregate :one
INSERT INTO price_aggregates_monthly (
    geo_area_id,
    metric_type,
    subject_id,
    month,
    median_amount,
    min_amount,
    max_amount,
    sample_size,
    confidence_score,
    calculated_at
) VALUES (
    $1::uuid,
    $2::varchar,
    $3::uuid,
    $4::date,
    $5::numeric,
    $6::numeric,
    $7::numeric,
    $8::integer,
    $9::numeric,
    $10::timestamptz
)
ON CONFLICT (geo_area_id, metric_type, subject_id, month) DO UPDATE SET
    median_amount = EXCLUDED.median_amount,
    min_amount = EXCLUDED.min_amount,
    max_amount = EXCLUDED.max_amount,
    sample_size = EXCLUDED.sample_size,
    confidence_score = EXCLUDED.confidence_score,
    calculated_at = EXCLUDED.calculated_at
RETURNING geo_area_id, metric_type, subject_id, month, median_amount, min_amount, max_amount, sample_size, confidence_score, calculated_at
`

type UpsertMonthlyPriceAggregateParams struct {
	GeoAreaID       pgtype.UUID        `json:"geo_area_id"`
	MetricType      string             `json:"metric_type"`
	SubjectID       pgtype.UUID        `json:"subject_id"`
	Month           pgtype.Date        `json:"month"`
	MedianAmount    pgtype.Numeric     `json:"median_amount"`
	MinAmount       pgtype.Numeric     `json:"min_amount"`
	MaxAmount       pgtype.Numeric     `json:"max_amount"`
	SampleSize      int32              `json:"sample_size"`
	ConfidenceScore pgtype.Numeric     `json:"confidence_score"`
	CalculatedAt    pgtype.Timestamptz `json:"calculated_at"`
}

func (q *Queries) UpsertMonthlyPriceAggregate(ctx context.Context, arg UpsertMonthlyPriceAggregateParams) (PriceAggregatesMonthly, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyPriceAggregate,
		arg.GeoAreaID,
		arg.MetricType,
		arg.SubjectID,
		arg.Month,
		arg.MedianAmount,
		arg.MinAmount,
		arg.MaxAmount,
		arg.SampleSize,
		arg.ConfidenceScore,
		arg.CalculatedAt,
	)
	var i PriceAggregatesMonthly
	err := row.Scan(
		&i.GeoAreaID,
		&i.MetricType,
		&i.SubjectID,
		&i.Month,
		&i.MedianAmount,
		&i.MinAmount,
		&i.MaxAmount,
		&i.SampleSize,
		&i.ConfidenceScore,
		&i.CalculatedAt,
	)
	return i, err
}
