// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products
WHERE id = $1::uuid
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductPrice = `-- name: DeleteProductPrice :execrows
DELETE FROM product_price_observations
WHERE id = $1::uuid
`

func (q *Queries) DeleteProductPrice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductPrice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProduct = `-- name: GetProduct :one
SELECT
    p.id,
    p.name,
    p.brand,
    p.barcode,
    p.reference_unit_code,
    p.is_generic,
    p.attributes,
    p.created_at,
    c.slug AS category_slug,
    c.name_i18n AS category_name_i18n
FROM products AS p
JOIN categories AS c ON c.id = p.category_id
WHERE p.id = $1::uuid
`

type GetProductRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Brand             *string            `json:"brand"`
	Barcode           *string            `json:"barcode"`
	ReferenceUnitCode string             `json:"reference_unit_code"`
	IsGeneric         bool               `json:"is_generic"`
	Attributes        []byte             `json:"attributes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CategorySlug      string             `json:"category_slug"`
	CategoryNameI18n  []byte             `json:"category_name_i18n"`
}

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.Barcode,
		&i.ReferenceUnitCode,
		&i.IsGeneric,
		&i.Attributes,
		&i.CreatedAt,
		&i.CategorySlug,
		&i.CategoryNameI18n,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT
    p.id,
    p.name,
    p.brand,
    p.barcode,
    p.reference_unit_code,
    p.is_generic,
    p.attributes,
    p.created_at,
    c.slug AS category_slug,
    c.name_i18n AS category_name_i18n
FROM products AS p
JOIN categories AS c ON c.id = p.category_id
WHERE p.barcode = $1::text
`

type GetProductByBarcodeRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Brand             *string            `json:"brand"`
	Barcode           *string            `json:"barcode"`
	ReferenceUnitCode string             `json:"reference_unit_code"`
	IsGeneric         bool               `json:"is_generic"`
	Attributes        []byte             `json:"attributes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CategorySlug      string             `json:"category_slug"`
	CategoryNameI18n  []byte             `json:"category_name_i18n"`
}

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode string) (GetProductByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i GetProductByBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.Barcode,
		&i.ReferenceUnitCode,
		&i.IsGeneric,
		&i.Attributes,
		&i.CreatedAt,
		&i.CategorySlug,
		&i.CategoryNameI18n,
	)
	return i, err
}

const getProductPrice = `-- name: GetProductPrice :one
SELECT
    o.id,
    o.product_id,
    o.amount,
    o.currency,
    o.quantity,
    o.unit_code,
    o.normalized_amount,
    o.is_promotion,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.source_record_id,
    l.id AS location_id,
    l.name AS location_name,
    l.address AS location_address,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM product_price_observations AS o
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.id = $1::uuid
`

type GetProductPriceRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   *string            `json:"source_record_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	LocationAddress  *string            `json:"location_address"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
}

func (q *Queries) GetProductPrice(ctx context.Context, id pgtype.UUID) (GetProductPriceRow, error) {
	row := q.db.QueryRow(ctx, getProductPrice, id)
	var i GetProductPriceRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.UnitCode,
		&i.NormalizedAmount,
		&i.IsPromotion,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.LocationID,
		&i.LocationName,
		&i.LocationAddress,
		&i.GeoAreaID,
		&i.GeoAreaName,
		&i.SourceID,
		&i.SourceName,
		&i.SourceKind,
	)
	return i, err
}

const listApprovedProductPrices = `-- name: ListApprovedProductPrices :many
SELECT
    o.id,
    o.product_id,
    o.amount,
    o.currency,
    o.quantity,
    o.unit_code,
    o.normalized_amount,
    o.is_promotion,
    o.observed_at,
    o.status,
    o.confidence_score,
    o.source_record_id,
    l.id AS location_id,
    l.name AS location_name,
    l.address AS location_address,
    g.id AS geo_area_id,
    g.name AS geo_area_name,
    s.id AS source_id,
    s.name AS source_name,
    s.kind AS source_kind
FROM product_price_observations AS o
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE o.product_id = $1::uuid
  AND o.status = 'approved'
  AND ($2::uuid IS NULL OR g.id = $2::uuid)
ORDER BY o.observed_at DESC, o.id
LIMIT $4::integer
OFFSET $3::integer
`

type ListApprovedProductPricesParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	GeoAreaID  pgtype.UUID `json:"geo_area_id"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListApprovedProductPricesRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   *string            `json:"source_record_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	LocationAddress  *string            `json:"location_address"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
}

func (q *Queries) ListApprovedProductPrices(ctx context.Context, arg ListApprovedProductPricesParams) ([]ListApprovedProductPricesRow, error) {
	rows, err := q.db.Query(ctx, listApprovedProductPrices,
		arg.ProductID,
		arg.GeoAreaID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedProductPricesRow{}
	for rows.Next() {
		var i ListApprovedProductPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitCode,
			&i.NormalizedAmount,
			&i.IsPromotion,
			&i.ObservedAt,
			&i.Status,
			&i.ConfidenceScore,
			&i.SourceRecordID,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.GeoAreaID,
			&i.GeoAreaName,
			&i.SourceID,
			&i.SourceName,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPriceObservations = `-- name: ListProductPriceObservations :many
SELECT
        o.id,
        o.product_id,
        o.amount,
        o.currency,
        o.quantity,
        o.unit_code,
        o.normalized_amount,
        o.is_promotion,
        o.observed_at,
        o.status,
        o.confidence_score,
        o.source_record_id,
        l.id AS location_id,
        l.name AS location_name,
        l.address AS location_address,
        g.id AS geo_area_id,
        g.name AS geo_area_name,
        s.id AS source_id,
        s.name AS source_name,
        s.kind AS source_kind
FROM product_price_observations AS o
JOIN locations AS l ON l.id = o.location_id
JOIN geo_areas AS g ON g.id = l.geo_area_id
JOIN sources AS s ON s.id = o.source_id
WHERE ($1::uuid IS NULL OR o.product_id = $1::uuid)
    AND ($2::uuid IS NULL OR g.id = $2::uuid)
    AND ($3::text IS NULL OR o.status::text = $3::text)
ORDER BY o.observed_at DESC, o.id
LIMIT $5::integer
OFFSET $4::integer
`

type ListProductPriceObservationsParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	GeoAreaID  pgtype.UUID `json:"geo_area_id"`
	Status     *string     `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type ListProductPriceObservationsRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   *string            `json:"source_record_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	LocationName     string             `json:"location_name"`
	LocationAddress  *string            `json:"location_address"`
	GeoAreaID        pgtype.UUID        `json:"geo_area_id"`
	GeoAreaName      string             `json:"geo_area_name"`
	SourceID         pgtype.UUID        `json:"source_id"`
	SourceName       string             `json:"source_name"`
	SourceKind       SourceKind         `json:"source_kind"`
}

func (q *Queries) ListProductPriceObservations(ctx context.Context, arg ListProductPriceObservationsParams) ([]ListProductPriceObservationsRow, error) {
	rows, err := q.db.Query(ctx, listProductPriceObservations,
		arg.ProductID,
		arg.GeoAreaID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductPriceObservationsRow{}
	for rows.Next() {
		var i ListProductPriceObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.UnitCode,
			&i.NormalizedAmount,
			&i.IsPromotion,
			&i.ObservedAt,
			&i.Status,
			&i.ConfidenceScore,
			&i.SourceRecordID,
			&i.LocationID,
			&i.LocationName,
			&i.LocationAddress,
			&i.GeoAreaID,
			&i.GeoAreaName,
			&i.SourceID,
			&i.SourceName,
			&i.SourceKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.name,
    p.brand,
    p.barcode,
    p.reference_unit_code,
    p.is_generic,
    p.attributes,
    p.created_at,
    c.slug AS category_slug,
    c.name_i18n AS category_name_i18n
FROM products AS p
JOIN categories AS c ON c.id = p.category_id
WHERE (
    $1::text IS NULL
    OR p.name ILIKE '%' || $1::text || '%'
    OR p.brand ILIKE '%' || $1::text || '%'
    OR p.barcode = $1::text
)
ORDER BY p.name, p.id
LIMIT $3::integer
OFFSET $2::integer
`

type ListProductsParams struct {
	Search     *string `json:"search"`
	PageOffset int32   `json:"page_offset"`
	PageSize   int32   `json:"page_size"`
}

type ListProductsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Brand             *string            `json:"brand"`
	Barcode           *string            `json:"barcode"`
	ReferenceUnitCode string             `json:"reference_unit_code"`
	IsGeneric         bool               `json:"is_generic"`
	Attributes        []byte             `json:"attributes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CategorySlug      string             `json:"category_slug"`
	CategoryNameI18n  []byte             `json:"category_name_i18n"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Search, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.Barcode,
			&i.ReferenceUnitCode,
			&i.IsGeneric,
			&i.Attributes,
			&i.CreatedAt,
			&i.CategorySlug,
			&i.CategoryNameI18n,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProductByBarcode = `-- name: UpsertProductByBarcode :one
INSERT INTO products (
    category_id,
    name,
    brand,
    barcode,
    reference_unit_code,
    is_generic,
    attributes
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::varchar,
    $5::varchar,
    $6::boolean,
    $7::jsonb
)
ON CONFLICT (barcode) WHERE barcode IS NOT NULL DO UPDATE SET
    category_id = EXCLUDED.category_id,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    reference_unit_code = EXCLUDED.reference_unit_code,
    is_generic = EXCLUDED.is_generic,
    attributes = EXCLUDED.attributes
RETURNING id, category_id, name, brand, barcode, reference_unit_code, is_generic, attributes, created_at
`

type UpsertProductByBarcodeParams struct {
	CategoryID        pgtype.UUID `json:"category_id"`
	Name              string      `json:"name"`
	Brand             *string     `json:"brand"`
	Barcode           string      `json:"barcode"`
	ReferenceUnitCode string      `json:"reference_unit_code"`
	IsGeneric         bool        `json:"is_generic"`
	Attributes        []byte      `json:"attributes"`
}

func (q *Queries) UpsertProductByBarcode(ctx context.Context, arg UpsertProductByBarcodeParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProductByBarcode,
		arg.CategoryID,
		arg.Name,
		arg.Brand,
		arg.Barcode,
		arg.ReferenceUnitCode,
		arg.IsGeneric,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Brand,
		&i.Barcode,
		&i.ReferenceUnitCode,
		&i.IsGeneric,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProductByID = `-- name: UpsertProductByID :one
INSERT INTO products (
    id,
    category_id,
    name,
    brand,
    barcode,
    reference_unit_code,
    is_generic,
    attributes
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::text,
    $6::varchar,
    $7::boolean,
    $8::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    barcode = EXCLUDED.barcode,
    reference_unit_code = EXCLUDED.reference_unit_code,
    is_generic = EXCLUDED.is_generic,
    attributes = EXCLUDED.attributes
RETURNING id, category_id, name, brand, barcode, reference_unit_code, is_generic, attributes, created_at
`

type UpsertProductByIDParams struct {
	ID                pgtype.UUID `json:"id"`
	CategoryID        pgtype.UUID `json:"category_id"`
	Name              string      `json:"name"`
	Brand             *string     `json:"brand"`
	Barcode           *string     `json:"barcode"`
	ReferenceUnitCode string      `json:"reference_unit_code"`
	IsGeneric         bool        `json:"is_generic"`
	Attributes        []byte      `json:"attributes"`
}

func (q *Queries) UpsertProductByID(ctx context.Context, arg UpsertProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProductByID,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Brand,
		arg.Barcode,
		arg.ReferenceUnitCode,
		arg.IsGeneric,
		arg.Attributes,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Brand,
		&i.Barcode,
		&i.ReferenceUnitCode,
		&i.IsGeneric,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProductPriceByID = `-- name: UpsertProductPriceByID :one
INSERT INTO product_price_observations (
    id,
    product_id,
    location_id,
    source_id,
    contributor_id,
    amount,
    currency,
    quantity,
    unit_code,
    normalized_amount,
    is_promotion,
    observed_at,
    status,
    confidence_score,
    source_record_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::numeric,
    $7::char(3),
    $8::numeric,
    $9::varchar,
    $10::numeric,
    $11::boolean,
    $12::timestamptz,
    $13::moderation_status,
    $14::numeric,
    $15::text
)
ON CONFLICT (id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    location_id = EXCLUDED.location_id,
    source_id = EXCLUDED.source_id,
    contributor_id = EXCLUDED.contributor_id,
    amount = EXCLUDED.amount,
    currency = EXCLUDED.currency,
    quantity = EXCLUDED.quantity,
    unit_code = EXCLUDED.unit_code,
    normalized_amount = EXCLUDED.normalized_amount,
    is_promotion = EXCLUDED.is_promotion,
    observed_at = EXCLUDED.observed_at,
    status = EXCLUDED.status,
    confidence_score = EXCLUDED.confidence_score,
    source_record_id = EXCLUDED.source_record_id
RETURNING id, product_id, location_id, source_id, contributor_id, amount, currency, quantity, unit_code, normalized_amount, is_promotion, observed_at, status, confidence_score, source_record_id, created_at
`

type UpsertProductPriceByIDParams struct {
	ID               pgtype.UUID        `json:"id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   *string            `json:"source_record_id"`
}

func (q *Queries) UpsertProductPriceByID(ctx context.Context, arg UpsertProductPriceByIDParams) (ProductPriceObservation, error) {
	row := q.db.QueryRow(ctx, upsertProductPriceByID,
		arg.ID,
		arg.ProductID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.UnitCode,
		arg.NormalizedAmount,
		arg.IsPromotion,
		arg.ObservedAt,
		arg.Status,
		arg.ConfidenceScore,
		arg.SourceRecordID,
	)
	var i ProductPriceObservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LocationID,
		&i.SourceID,
		&i.ContributorID,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.UnitCode,
		&i.NormalizedAmount,
		&i.IsPromotion,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProductPriceBySourceRecord = `-- name: UpsertProductPriceBySourceRecord :one
INSERT INTO product_price_observations (
    product_id,
    location_id,
    source_id,
    contributor_id,
    amount,
    currency,
    quantity,
    unit_code,
    normalized_amount,
    is_promotion,
    observed_at,
    status,
    confidence_score,
    source_record_id
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::numeric,
    $6::char(3),
    $7::numeric,
    $8::varchar,
    $9::numeric,
    $10::boolean,
    $11::timestamptz,
    $12::moderation_status,
    $13::numeric,
    $14::text
)
ON CONFLICT (source_id, source_record_id) WHERE source_record_id IS NOT NULL DO UPDATE SET
    product_id = EXCLUDED.product_id,
    location_id = EXCLUDED.location_id,
    contributor_id = EXCLUDED.contributor_id,
    amount = EXCLUDED.amount,
    currency = EXCLUDED.currency,
    quantity = EXCLUDED.quantity,
    unit_code = EXCLUDED.unit_code,
    normalized_amount = EXCLUDED.normalized_amount,
    is_promotion = EXCLUDED.is_promotion,
    observed_at = EXCLUDED.observed_at,
    status = EXCLUDED.status,
    confidence_score = EXCLUDED.confidence_score
RETURNING id, product_id, location_id, source_id, contributor_id, amount, currency, quantity, unit_code, normalized_amount, is_promotion, observed_at, status, confidence_score, source_record_id, created_at
`

type UpsertProductPriceBySourceRecordParams struct {
	ProductID        pgtype.UUID        `json:"product_id"`
	LocationID       pgtype.UUID        `json:"location_id"`
	SourceID         pgtype.UUID        `json:"source_id"`
	ContributorID    pgtype.UUID        `json:"contributor_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitCode         string             `json:"unit_code"`
	NormalizedAmount pgtype.Numeric     `json:"normalized_amount"`
	IsPromotion      bool               `json:"is_promotion"`
	ObservedAt       pgtype.Timestamptz `json:"observed_at"`
	Status           ModerationStatus   `json:"status"`
	ConfidenceScore  pgtype.Numeric     `json:"confidence_score"`
	SourceRecordID   string             `json:"source_record_id"`
}

func (q *Queries) UpsertProductPriceBySourceRecord(ctx context.Context, arg UpsertProductPriceBySourceRecordParams) (ProductPriceObservation, error) {
	row := q.db.QueryRow(ctx, upsertProductPriceBySourceRecord,
		arg.ProductID,
		arg.LocationID,
		arg.SourceID,
		arg.ContributorID,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.UnitCode,
		arg.NormalizedAmount,
		arg.IsPromotion,
		arg.ObservedAt,
		arg.Status,
		arg.ConfidenceScore,
		arg.SourceRecordID,
	)
	var i ProductPriceObservation
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LocationID,
		&i.SourceID,
		&i.ContributorID,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.UnitCode,
		&i.NormalizedAmount,
		&i.IsPromotion,
		&i.ObservedAt,
		&i.Status,
		&i.ConfidenceScore,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}
