// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: references.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCategoryBySlug = `-- name: UpsertCategoryBySlug :one
INSERT INTO categories (parent_id, slug, name_i18n)
VALUES (
    $1::uuid,
    $2::text,
    $3::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    name_i18n = EXCLUDED.name_i18n
RETURNING id, parent_id, slug, name_i18n
`

type UpsertCategoryBySlugParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Slug     string      `json:"slug"`
	NameI18n []byte      `json:"name_i18n"`
}

func (q *Queries) UpsertCategoryBySlug(ctx context.Context, arg UpsertCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, upsertCategoryBySlug, arg.ParentID, arg.Slug, arg.NameI18n)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameI18n,
	)
	return i, err
}

const upsertFuelTypeByCode = `-- name: UpsertFuelTypeByCode :one
INSERT INTO fuel_types (code, name_i18n, energy)
VALUES (
    $1::varchar,
    $2::jsonb,
    $3::varchar
)
ON CONFLICT (code) DO UPDATE SET
    name_i18n = EXCLUDED.name_i18n,
    energy = EXCLUDED.energy
RETURNING id, code, name_i18n, energy
`

type UpsertFuelTypeByCodeParams struct {
	Code     string `json:"code"`
	NameI18n []byte `json:"name_i18n"`
	Energy   string `json:"energy"`
}

func (q *Queries) UpsertFuelTypeByCode(ctx context.Context, arg UpsertFuelTypeByCodeParams) (FuelType, error) {
	row := q.db.QueryRow(ctx, upsertFuelTypeByCode, arg.Code, arg.NameI18n, arg.Energy)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameI18n,
		&i.Energy,
	)
	return i, err
}

const upsertGeoAreaByCode = `-- name: UpsertGeoAreaByCode :one
INSERT INTO geo_areas (parent_id, type, code, name, country_code, centroid)
VALUES (
    $1::uuid,
    $2::varchar,
    $3::varchar,
    $4::text,
        $5::char(2),
        CASE WHEN $6::double precision IS NULL OR $7::double precision IS NULL THEN NULL
            ELSE ST_SetSRID(ST_MakePoint($7::double precision, $6::double precision), 4326)::geography END
)
ON CONFLICT (type, country_code, code) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    name = EXCLUDED.name,
    centroid = EXCLUDED.centroid
RETURNING id, parent_id, type, code, name, country_code, geometry, centroid
`

type UpsertGeoAreaByCodeParams struct {
	ParentID    pgtype.UUID `json:"parent_id"`
	Type        string      `json:"type"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Latitude    *float64    `json:"latitude"`
	Longitude   *float64    `json:"longitude"`
}

func (q *Queries) UpsertGeoAreaByCode(ctx context.Context, arg UpsertGeoAreaByCodeParams) (GeoArea, error) {
	row := q.db.QueryRow(ctx, upsertGeoAreaByCode,
		arg.ParentID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i GeoArea
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Geometry,
		&i.Centroid,
	)
	return i, err
}

const upsertGeoAreaByID = `-- name: UpsertGeoAreaByID :one
INSERT INTO geo_areas (id, parent_id, type, code, name, country_code, centroid)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::varchar,
    $4::varchar,
    $5::text,
        $6::char(2),
        CASE WHEN $7::double precision IS NULL OR $8::double precision IS NULL THEN NULL
            ELSE ST_SetSRID(ST_MakePoint($8::double precision, $7::double precision), 4326)::geography END
)
ON CONFLICT (id) DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    type = EXCLUDED.type,
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    country_code = EXCLUDED.country_code,
    centroid = EXCLUDED.centroid
RETURNING id, parent_id, type, code, name, country_code, geometry, centroid
`

type UpsertGeoAreaByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Type        string      `json:"type"`
	Code        *string     `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Latitude    *float64    `json:"latitude"`
	Longitude   *float64    `json:"longitude"`
}

func (q *Queries) UpsertGeoAreaByID(ctx context.Context, arg UpsertGeoAreaByIDParams) (GeoArea, error) {
	row := q.db.QueryRow(ctx, upsertGeoAreaByID,
		arg.ID,
		arg.ParentID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i GeoArea
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Geometry,
		&i.Centroid,
	)
	return i, err
}

const upsertLocationByID = `-- name: UpsertLocationByID :one
INSERT INTO locations (id, merchant_id, geo_area_id, name, address, position, external_ref)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
        $5::text,
        CASE WHEN $6::double precision IS NULL OR $7::double precision IS NULL THEN NULL
            ELSE ST_SetSRID(ST_MakePoint($7::double precision, $6::double precision), 4326)::geography END,
    $8::text
)
ON CONFLICT (id) DO UPDATE SET
    merchant_id = EXCLUDED.merchant_id,
    geo_area_id = EXCLUDED.geo_area_id,
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    position = EXCLUDED.position,
    external_ref = EXCLUDED.external_ref
RETURNING id, merchant_id, geo_area_id, name, address, position, external_ref, created_at
`

type UpsertLocationByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	MerchantID  pgtype.UUID `json:"merchant_id"`
	GeoAreaID   pgtype.UUID `json:"geo_area_id"`
	Name        string      `json:"name"`
	Address     *string     `json:"address"`
	Latitude    *float64    `json:"latitude"`
	Longitude   *float64    `json:"longitude"`
	ExternalRef *string     `json:"external_ref"`
}

func (q *Queries) UpsertLocationByID(ctx context.Context, arg UpsertLocationByIDParams) (Location, error) {
	row := q.db.QueryRow(ctx, upsertLocationByID,
		arg.ID,
		arg.MerchantID,
		arg.GeoAreaID,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.ExternalRef,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.GeoAreaID,
		&i.Name,
		&i.Address,
		&i.Position,
		&i.ExternalRef,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMerchantByID = `-- name: UpsertMerchantByID :one
INSERT INTO merchants (id, name, website_url)
VALUES (
    $1::uuid,
    $2::text,
    $3::text
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    website_url = EXCLUDED.website_url
RETURNING id, name, website_url, created_at
`

type UpsertMerchantByIDParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	WebsiteUrl *string     `json:"website_url"`
}

func (q *Queries) UpsertMerchantByID(ctx context.Context, arg UpsertMerchantByIDParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, upsertMerchantByID, arg.ID, arg.Name, arg.WebsiteUrl)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebsiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSourceByID = `-- name: UpsertSourceByID :one
INSERT INTO sources (
    id, name, kind, homepage_url, license_name, license_url, attribution, is_active
) VALUES (
    $1::uuid,
    $2::text,
    $3::source_kind,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::boolean
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    homepage_url = EXCLUDED.homepage_url,
    license_name = EXCLUDED.license_name,
    license_url = EXCLUDED.license_url,
    attribution = EXCLUDED.attribution,
    is_active = EXCLUDED.is_active
RETURNING id, name, kind, homepage_url, license_name, license_url, attribution, is_active, created_at
`

type UpsertSourceByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Kind        SourceKind  `json:"kind"`
	HomepageUrl *string     `json:"homepage_url"`
	LicenseName *string     `json:"license_name"`
	LicenseUrl  *string     `json:"license_url"`
	Attribution *string     `json:"attribution"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpsertSourceByID(ctx context.Context, arg UpsertSourceByIDParams) (Source, error) {
	row := q.db.QueryRow(ctx, upsertSourceByID,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.HomepageUrl,
		arg.LicenseName,
		arg.LicenseUrl,
		arg.Attribution,
		arg.IsActive,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.HomepageUrl,
		&i.LicenseName,
		&i.LicenseUrl,
		&i.Attribution,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUnitByCode = `-- name: UpsertUnitByCode :one
INSERT INTO units (code, dimension, to_base_factor)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::numeric
)
ON CONFLICT (code) DO UPDATE SET
    dimension = EXCLUDED.dimension,
    to_base_factor = EXCLUDED.to_base_factor
RETURNING code, dimension, to_base_factor
`

type UpsertUnitByCodeParams struct {
	Code         string         `json:"code"`
	Dimension    string         `json:"dimension"`
	ToBaseFactor pgtype.Numeric `json:"to_base_factor"`
}

func (q *Queries) UpsertUnitByCode(ctx context.Context, arg UpsertUnitByCodeParams) (Unit, error) {
	row := q.db.QueryRow(ctx, upsertUnitByCode, arg.Code, arg.Dimension, arg.ToBaseFactor)
	var i Unit
	err := row.Scan(&i.Code, &i.Dimension, &i.ToBaseFactor)
	return i, err
}
