// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id=$1::uuid
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFuelType = `-- name: DeleteFuelType :execrows
DELETE FROM fuel_types WHERE id=$1::uuid
`

func (q *Queries) DeleteFuelType(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFuelType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGeoArea = `-- name: DeleteGeoArea :execrows
DELETE FROM geo_areas WHERE id=$1::uuid
`

func (q *Queries) DeleteGeoArea(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeoArea, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations WHERE id=$1::uuid
`

func (q *Queries) DeleteLocation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMerchant = `-- name: DeleteMerchant :execrows
DELETE FROM merchants WHERE id=$1::uuid
`

func (q *Queries) DeleteMerchant(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMerchant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSource = `-- name: DeleteSource :execrows
DELETE FROM sources WHERE id=$1::uuid
`

func (q *Queries) DeleteSource(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnit = `-- name: DeleteUnit :execrows
DELETE FROM units WHERE code=$1::varchar
`

func (q *Queries) DeleteUnit(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnit, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, slug, name_i18n FROM categories WHERE id=$1::uuid
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameI18n,
	)
	return i, err
}

const getFuelType = `-- name: GetFuelType :one
SELECT id, code, name_i18n, energy FROM fuel_types WHERE id=$1::uuid
`

func (q *Queries) GetFuelType(ctx context.Context, id pgtype.UUID) (FuelType, error) {
	row := q.db.QueryRow(ctx, getFuelType, id)
	var i FuelType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.NameI18n,
		&i.Energy,
	)
	return i, err
}

const getGeoArea = `-- name: GetGeoArea :one
SELECT id, parent_id, type, code, name, country_code,
    COALESCE(ST_Y(centroid::geometry), 'NaN'::double precision) AS latitude,
    COALESCE(ST_X(centroid::geometry), 'NaN'::double precision) AS longitude
FROM geo_areas WHERE id = $1::uuid
`

type GetGeoAreaRow struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Type        string      `json:"type"`
	Code        *string     `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Latitude    interface{} `json:"latitude"`
	Longitude   interface{} `json:"longitude"`
}

func (q *Queries) GetGeoArea(ctx context.Context, id pgtype.UUID) (GetGeoAreaRow, error) {
	row := q.db.QueryRow(ctx, getGeoArea, id)
	var i GetGeoAreaRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id,merchant_id,geo_area_id,name,address,external_ref,created_at,
COALESCE(ST_Y(position::geometry), 'NaN'::double precision) AS latitude,
COALESCE(ST_X(position::geometry), 'NaN'::double precision) AS longitude
FROM locations WHERE id=$1::uuid
`

type GetLocationRow struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	GeoAreaID   pgtype.UUID        `json:"geo_area_id"`
	Name        string             `json:"name"`
	Address     *string            `json:"address"`
	ExternalRef *string            `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Latitude    interface{}        `json:"latitude"`
	Longitude   interface{}        `json:"longitude"`
}

func (q *Queries) GetLocation(ctx context.Context, id pgtype.UUID) (GetLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i GetLocationRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.GeoAreaID,
		&i.Name,
		&i.Address,
		&i.ExternalRef,
		&i.CreatedAt,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, website_url, created_at FROM merchants WHERE id=$1::uuid
`

func (q *Queries) GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebsiteUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, name, kind, homepage_url, license_name, license_url, attribution, is_active, created_at FROM sources WHERE id=$1::uuid
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.HomepageUrl,
		&i.LicenseName,
		&i.LicenseUrl,
		&i.Attribution,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT code, dimension, to_base_factor FROM units WHERE code=$1::varchar
`

func (q *Queries) GetUnit(ctx context.Context, code string) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, code)
	var i Unit
	err := row.Scan(&i.Code, &i.Dimension, &i.ToBaseFactor)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, slug, name_i18n FROM categories ORDER BY slug LIMIT $2::integer OFFSET $1::integer
`

type ListCategoriesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.NameI18n,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelTypes = `-- name: ListFuelTypes :many
SELECT id, code, name_i18n, energy FROM fuel_types ORDER BY code LIMIT $2::integer OFFSET $1::integer
`

type ListFuelTypesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListFuelTypes(ctx context.Context, arg ListFuelTypesParams) ([]FuelType, error) {
	rows, err := q.db.Query(ctx, listFuelTypes, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelType{}
	for rows.Next() {
		var i FuelType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.NameI18n,
			&i.Energy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeoAreas = `-- name: ListGeoAreas :many
SELECT id, parent_id, type, code, name, country_code,
    COALESCE(ST_Y(centroid::geometry), 'NaN'::double precision) AS latitude,
    COALESCE(ST_X(centroid::geometry), 'NaN'::double precision) AS longitude
FROM geo_areas ORDER BY name, id LIMIT $2::integer OFFSET $1::integer
`

type ListGeoAreasParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListGeoAreasRow struct {
	ID          pgtype.UUID `json:"id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Type        string      `json:"type"`
	Code        *string     `json:"code"`
	Name        string      `json:"name"`
	CountryCode string      `json:"country_code"`
	Latitude    interface{} `json:"latitude"`
	Longitude   interface{} `json:"longitude"`
}

func (q *Queries) ListGeoAreas(ctx context.Context, arg ListGeoAreasParams) ([]ListGeoAreasRow, error) {
	rows, err := q.db.Query(ctx, listGeoAreas, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeoAreasRow{}
	for rows.Next() {
		var i ListGeoAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id,merchant_id,geo_area_id,name,address,external_ref,created_at,
COALESCE(ST_Y(position::geometry), 'NaN'::double precision) AS latitude,
COALESCE(ST_X(position::geometry), 'NaN'::double precision) AS longitude
FROM locations ORDER BY name,id LIMIT $2::integer OFFSET $1::integer
`

type ListLocationsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListLocationsRow struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	GeoAreaID   pgtype.UUID        `json:"geo_area_id"`
	Name        string             `json:"name"`
	Address     *string            `json:"address"`
	ExternalRef *string            `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Latitude    interface{}        `json:"latitude"`
	Longitude   interface{}        `json:"longitude"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationsRow{}
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.GeoAreaID,
			&i.Name,
			&i.Address,
			&i.ExternalRef,
			&i.CreatedAt,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, name, website_url, created_at FROM merchants ORDER BY name,id LIMIT $2::integer OFFSET $1::integer
`

type ListMerchantsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebsiteUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, name, kind, homepage_url, license_name, license_url, attribution, is_active, created_at FROM sources ORDER BY name, id LIMIT $2::integer OFFSET $1::integer
`

type ListSourcesParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListSources(ctx context.Context, arg ListSourcesParams) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.HomepageUrl,
			&i.LicenseName,
			&i.LicenseUrl,
			&i.Attribution,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT code, dimension, to_base_factor FROM units ORDER BY code LIMIT $2::integer OFFSET $1::integer
`

type ListUnitsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.Code, &i.Dimension, &i.ToBaseFactor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryByID = `-- name: UpsertCategoryByID :one
INSERT INTO categories(id,parent_id,slug,name_i18n) VALUES($1::uuid,$2::uuid,$3::text,$4::jsonb)
ON CONFLICT(id) DO UPDATE SET parent_id=EXCLUDED.parent_id,slug=EXCLUDED.slug,name_i18n=EXCLUDED.name_i18n RETURNING id
`

type UpsertCategoryByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Slug     string      `json:"slug"`
	NameI18n []byte      `json:"name_i18n"`
}

func (q *Queries) UpsertCategoryByID(ctx context.Context, arg UpsertCategoryByIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCategoryByID,
		arg.ID,
		arg.ParentID,
		arg.Slug,
		arg.NameI18n,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertFuelTypeByID = `-- name: UpsertFuelTypeByID :one
INSERT INTO fuel_types(id,code,name_i18n,energy) VALUES($1::uuid,$2::varchar,$3::jsonb,$4::varchar)
ON CONFLICT(id) DO UPDATE SET code=EXCLUDED.code,name_i18n=EXCLUDED.name_i18n,energy=EXCLUDED.energy RETURNING id
`

type UpsertFuelTypeByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	Code     string      `json:"code"`
	NameI18n []byte      `json:"name_i18n"`
	Energy   string      `json:"energy"`
}

func (q *Queries) UpsertFuelTypeByID(ctx context.Context, arg UpsertFuelTypeByIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertFuelTypeByID,
		arg.ID,
		arg.Code,
		arg.NameI18n,
		arg.Energy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
